server:
  port: 80
client_id: ******
client_secret: *******
Redirect_uri: *******
spring:
  datasource:
    url: jdbc:mysql://****:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
endpoint: http://oss-cn-beijing.aliyuncs.com
accessKeyId: ****
accessKeySecret: ******
bucketName: shuixin

logging:
  file: logs/community.log
  max-history: 30
  max-size: 100MB
  level:
    root: info







