server:
  port: 80
client_id: Iv1.b7d0686e97d9e912
client_secret: bedefe6865bcce7df9d367373a0d54fce2d37ff7
Redirect_uri: http://47.95.146.87/callback
spring:
  datasource:
    url: jdbc:mysql://47.95.146.87:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
endpoint: http://oss-cn-beijing.aliyuncs.com
accessKeyId: LTAIlAHWpVWuoRQH
accessKeySecret: Zg6oKK5WFdMiN8IEmKPAUWAvGUxfzG
bucketName: shuixin

logging:
  file: logs/community.log
  max-history: 30
  max-size: 100MB
  level:
    root: info







