server:
  port: 80 
client_id: Iv1.b7d0686e97d9e912
client_secret: bedefe6865bcce7df9d367373a0d54fce2d37ff7
Redirect_uri: http://www.wast.club/callback


#Baidu
Baidu_client_id: 9LuOVa1xvTbgkNdQvYIBgdIM
Baidu_client_secret: hWzSGQYvETOnee6kmiAHtAQf6Q4crR3s
Baidu_Redirect_uri: http://www.wast.club/baiducallback

#qq
QQ_client_id: 101802971
QQ_client_secret: 772adebaf15b637a2d2e6aed6081895f
QQ_Redirect_uri: http://www.wast.club/qqcallback

spring:
  datasource:
    url: jdbc:mysql://106.75.109.78:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1003Lv@@
    driver-class-name: com.mysql.jdbc.Driver
    messages:
      basename: i18n.message
    thymeleaf:
        cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: life.lv.community.model
  mapper-locations: classpath:mapper/*.xml
endpoint: http://oss-cn-beijing.aliyuncs.com
accessKeyId: LTAIlAHWpVWuoRQH
accessKeySecret: Zg6oKK5WFdMiN8IEmKPAUWAvGUxfzG
bucketName: shuixin

logging:
  file: logs/community.log
  max-history: 30
  max-size: 100MB
  level:
    root: info







