server:
  port: 8887


#github
client_id: ***************
client_secret: *************
Redirect_uri: ************


#Baidu
Baidu_client_id: ************
Baidu_client_secret: ***************
Baidu_Redirect_uri: ***************

#qq
QQ_client_id: 101802971
QQ_client_secret: ****************
QQ_Redirect_uri: *****************

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: *********
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 106.75.109.78
    port: 6379
    password: 123456
  thymeleaf:
    cache: false
  messages:
    basename: i18n.message
  # 邮箱
  mail:
    username: you@example.com
    password: *************
    host: smtp.qq.com



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: life.lv.community.model
  mapper-locations: classpath:mapper/*.xml

endpoint: ************
accessKeyId: *********
accessKeySecret: ************
bucketName: **********

logging:
  file: logs/community.log
  max-history: 15
  max-size: 100MB
  level:
    root: info
    life:
      lv:
        community:
          mapper: debug





