server:
  port: 8887
client_id: Iv1.b9785368af06692f
client_secret: ff05fe28f0287463020a18bfd43313639dd63e6b
Redirect_uri: http://localhost:8887/callback
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: rjxy
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: 47.95.146.87
#    port: 6379
#    password: 12345678
  thymeleaf:
    cache: false
  messages:
    basename: i18n.message
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: life.lv.community.model
  mapper-locations: classpath:mapper/*.xml

endpoint: ***************
accessKeyId: ***********
accessKeySecret: **************
bucketName: *****

logging:
  file: logs/community.log
  max-history: 15
  max-size: 100MB
  level:
    root: info
    life:
      lv:
        community:
          mapper: debug





