server:
  port: 8887
client_id: Iv1.b7d0686e97d9e912
client_secret: bedefe6865bcce7df9d367373a0d54fce2d37ff7
Redirect_uri: http://localhost:8887/callback
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: rjxy
    driver-class-name: com.mysql.cj.jdbc.Driver