server:
  port: 80
  
#github
client_id: *********
client_secret: *********************
Redirect_uri: *****************

#Baidu
Baidu_client_id: *****************
Baidu_client_secret: ****************
Baidu_Redirect_uri: ******************


#qq
QQ_client_id: ************
QQ_client_secret: ***************
QQ_Redirect_uri: ****************



spring:
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: ********
    driver-class-name: com.mysql.jdbc.Driver
  #redis
  redis:
    host: ************
    port: ****
    password: ********
  messages:
    basename: i18n.message
  thymeleaf:
    cache: false
  # 邮箱
  mail:
    username: you@example.com
    password: *******
    host: smtp.exmail.qq.com
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: com.sun.mail.util.MailSSLSocketFactory
              fallback: false



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: life.lv.community.model
  mapper-locations: classpath:mapper/*.xml

#alioss
endpoint: *****************
accessKeyId: ************
accessKeySecret: ***********
bucketName: ********

logging:
  file: logs/community.log
  max-history: 30
  max-size: 100MB
  level:
    root: info







