server:
  port: 80
  
#github
client_id: Iv1.b7d0686e97d9e912
client_secret: bedefe6865bcce7df9d367373a0d54fce2d37ff7
Redirect_uri: http://www.wast.club/callback

#Baidu
Baidu_client_id: 9LuOVa1xvTbgkNdQvYIBgdIM
Baidu_client_secret: hWzSGQYvETOnee6kmiAHtAQf6Q4crR3s
Baidu_Redirect_uri: http://www.wast.club/baiducallback


#qq
QQ_client_id: 101848461
QQ_client_secret: 73838b3287ea98e9eb84b094188de3d1
QQ_Redirect_uri: http://www.main.wast.club/qqcallback



spring:
  #mysql
  datasource:
    url: jdbc:mysql://39.106.112.85:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Lv1003@@
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatabookHikariCP
      max-lifetime: 120000
      connection-test-query: SELECT 1
      connection-timeout: 30000
  #redis
  redis:
    host: 39.106.112.85
    port: 6379
    password: Lv1003@@
  messages:
    basename: i18n.message
  thymeleaf:
    cache: false
  # 邮箱
  mail:
    username: community@wast.club
    password: 18639760875Lv
    host: smtp.exmail.qq.com
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: com.sun.mail.util.MailSSLSocketFactory
              fallback: false



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: life.lv.community.model
  mapper-locations: classpath:mapper/*.xml

endpoint: http://oss-cn-beijing.aliyuncs.com
accessKeyId: LTAIlAHWpVWuoRQH
accessKeySecret: Zg6oKK5WFdMiN8IEmKPAUWAvGUxfzG
bucketName: shuixin

logging:
  file: logs/community.log
  max-history: 30
  max-size: 100MB
  level:
    root: info







