server:
  port: 8887
client_id: xxxxxxxxxxxxxxxxxx
client_secret: xxxxxxxxxxxxxxxxxxxxx
Redirect_uri: xxxxxxxxxxxxxxxxxxxxxx
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: rjxy
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
endpoint: xxxxxxxxxxxxxxxxxxxxxx
accessKeyId: xxxxxxxxxxxxxxxxxxx
accessKeySecret: xxxxxxxxxxxxxxxxx
bucketName: xxxxxxxxxxxxxx

logging:
  file: logs/community.log
  max-history: 15
  max-size: 100MB
  level:
    root: info
    life:
      lv:
        community:
          mapper: debug







