package life.lv.community.model;

public class QuestionWithBLOBs extends Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.description
     *
     * @mbg.generated Thu Aug 29 16:23:02 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.like_used
     *
     * @mbg.generated Thu Aug 29 16:23:02 CST 2019
     */
    private String likeUsed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.description
     *
     * @return the value of question.description
     *
     * @mbg.generated Thu Aug 29 16:23:02 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.description
     *
     * @param description the value for question.description
     *
     * @mbg.generated Thu Aug 29 16:23:02 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.like_used
     *
     * @return the value of question.like_used
     *
     * @mbg.generated Thu Aug 29 16:23:02 CST 2019
     */
    public String getLikeUsed() {
        return likeUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.like_used
     *
     * @param likeUsed the value for question.like_used
     *
     * @mbg.generated Thu Aug 29 16:23:02 CST 2019
     */
    public void setLikeUsed(String likeUsed) {
        this.likeUsed = likeUsed == null ? null : likeUsed.trim();
    }
}